### ISSUE TITLE
Unable to delete last tag of an entity using navigator client

### ISSUE THREAD

**Issue by gokulavasan** [cloudera/navigator-sdk#44]
I am using 1.0 version of navigator-sdk-model/client and Navigator 2.4.1. When I try to delete the last tag in an entity using the client, the operation fails to change the metadata. It works if there is at least one tag left after deletion. But I am able to delete the last tag in the UI. Code used to delete tag is provided below.

      MyEntity myEntity = new MyEntity(ENTITY_NAME);
      myEntity.removeTags(args[1]);
      navPlugin.write(myEntity);

**Comment by changhiskhan** [comment]
I will have to see whether the error is client or server side. It'll be early next week before I'll be able to have time to take a look. In the mean time, try one of the following arounds:

1. Try to use the override tags instead of remove tags
2. You can also send a PUT request to /entities/{id}  (this is basically what the UI does)

**Comment by changhiskhan** [comment]
As per off-github convo, this has been fixed server side in the upcoming release. Closing this issue for now, can re-open if necessary.
